[project]
name = "deye-agent"
version = "0.2.0"
description = "Deye Inverter Command Line Tool and Monitoring"
authors = [
  {name = "khvalera", email = "khvalera@ukr.net"}
]
requires-python = ">=3.6"
license = {text = "Apache-2.0"}

[project.scripts]
deye-agent = "deye_agent.cli:main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
