# Show additional data
REGISTERS_FILE=/etc/deye-agent/registers.yaml
DEBUG=false

# Connecting to the inverter
RECONNECT_DELAY = 2.0
PORT     = "/dev/ttyUSB0"
BAUDRATE = 9600
SLAVE_ID = 1

# MQTT
MQTT_ENABLED=true
MQTT_HOST=127.0.0.1
MQTT_PORT=1883
MQTT_USERNAME=deye
MQTT_PASSWORD=passw
MQTT_TOPIC=solar/deye

# Monitoring
UPDATE_INTERVAL=60

# Notifications EMAIL
NOTIFY_EMAIL_ENABLED=false
NOTIFY_EMAIL_TO=youremail@example.com
NOTIFY_EMAIL_FROM=deye-agent@example.com
NOTIFY_EMAIL_SMTP_SERVER=smtp.example.com
NOTIFY_EMAIL_SMTP_PORT=587
NOTIFY_EMAIL_SMTP_USER=smtp_user
NOTIFY_EMAIL_SMTP_PASSWORD=smtp_password

# Notifications via Matrix
NOTIFY_MATRIX_ENABLED=false
NOTIFY_MATRIX_HOMESERVER=https://matrix.org
NOTIFY_MATRIX_ACCESS_TOKEN=YOUR_ACCESS_TOKEN
NOTIFY_MATRIX_ROOM_ID=!yourRoomId:matrix.org
